# The following options are all related to the clickable chat feature.
# This display a set of commands in the foramt of "(set tp rm)" that correlate
# to the command line options for each named waypoint. Only commands with for
# which the user has permission will be displayed.
clickableChat:
  # Enable or disable the clickable chat commands.
  useClickableChat: true

  # If true the clicks will run the commands immediately, if false it will
  # put command suggestions into the chat box. The "rm" command will always
  # use suggestions to prevent accidental removal of waypoints.
  clicksRunCommands: true

  # A limitation of Geyser plugin is that it doesn't support clickable chat.
  # The below option attemps to hide clickable chat options from these users
  # so it doesn't clutter their output, but they can still type the commands.
  hideGeyserUsers: true
  geyserPluginName: Geyser-Spigot
  geyserUsernamePrefix: .

# Following are some customizable responses for user input.
responseMessages:
  waypointNotExist: Waypoint does not exist
  playerCmdOnly: This command can only be run by a player.
  noPermission: Player does not have permission
  waypointLimitExceeded: Waypoint limit exceeded
  exceededServerMax: Exceeded server maximum waypoint limit

# The following is used to enable / disable the automatic update checker.
# This does not download updates, it only makes a call to the Spigot API
# to see if a new version is available. It's only done once during plugin load.
checkForUpdates: true

# Waypoints maintains a per-user count of both public and private waypoints. The
# following setting defines how many public / private waypoints are allowed per user.
# These are the values that are used unless a per-user limit is defined with permissions.
# Use a large value to effectively disable default limits.
defaultPublicWaypointLimit: 5
defaultPrivateWaypointLimit: 20

# The maximum total number of all public waypoints on the server. Even if a user is under
# their per-user limit they will not be able to add waypoints if the total count meets or exceeds
# this limit, unless they have admin permission or is an op.
serverMaxPublicWaypointLimit: 20

# Should the output of "wp list" be sorted by waypoint name?
sortWaypointList: true