# The following options are all related to the clickable chat feature.
# This display a set of commands in the foramt of "(set tp rm)" that correlate
# to the command line options for each named waypoint. Only commands with for
# which the user has permission will be displayed.
clickableChat:
  # Enable or disable the clickable chat commands.
  useClickableChat: true

  # If true the clicks will run the commands immediately, if false it will
  # put command suggestions into the chat box. The "rm" command will always
  # use suggestions to prevent accidental removal of waypoints.
  clicksRunCommands: true

  # A limitation of Geyser plugin is that it doesn't support clickable chat.
  # The below option attemps to hide clickable chat options from these users
  # so it doesn't clutter their output, but they can still type the commands.
  hideGeyserUsers: true
  geyserPluginName: Geyser-Spigot
  geyserUsernamePrefix: .

# Following are some customizable responses for user input.
responseMessages:
  waypointNotExist: Waypoint does not exist
  playerCmdOnly: This command can only be run by a player.
  noPermission: Player does not have permission

# The following is used enable / disable the automtic update checker.
# This does not download updates, it only makes a call to the Spigot API
# to see if a new version is available. It's only done once during plugin load.
checkForUpdates: true
