name: Test build of plugin

on:
  push:
    branches:
      - add_workflow
      - main
  pull_request:
    branches:
      - main

jobs:
  tag-new-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # - name: Set package version env variable
      #   run: |
      #     echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Check for Tag
        run: |
          RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          if git show-ref --tags --verify --quiet "refs/tags/${RELEASE_VERSION}"; then
            echo "Tag ${TAG} exists"
          else
            echo "Tag ${TAG} does not exist - creating new tag"
          fi
