name: Test build of plugin

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tag-new-versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: salsify/action-detect-and-tag-new-version@v2
        with:
          version-command: |
            mvn help:evaluate -Dexpression=project.version -q -DforceStdout
