name: Test build of plugin

on:
  push:
    branches:
      - '*'
      - '!main'
  pull_request:
    branches:
      - '*'
      - '!main'

jobs:
  test-build-plugin:
    runs-on: ubuntu-latest
    
    steps:
      - name: Test plugin build
        uses: ./.github/workflows/build_plugin.yml