name: Test build of plugin

on:
  push:
    branches:
      - '*'
      - '!main'
  pull_request:
    branches:
      - '*'
      - '!main'

jobs:
  build-plugin:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Set package version env variable
      run: |
        echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Waypoints-${{ env.RELEASE_VERSION }}.jar
        path: target/Waypoints-${{ env.RELEASE_VERSION }}.jar